Updates project to work with Swift 5.0/Xcode 10.2
PromiseKit/MapKit pull request #7
Opened 2019-04-02 19:05 UTC by aaronbrethorst

2019-04-02 19:51 UTC, mxcl requested changes

2019-04-02 19:51 UTC, mxcl commented on PMKMapKit.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
Needs to be 4.0.

2019-04-02 19:51 UTC, mxcl commented on PMKMapKit.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
Needs to be 4.0.

2019-04-02 19:51 UTC, mxcl commented on PMKMapKit.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
Needs to be 4.0.

2019-04-02 19:51 UTC, mxcl commented on PMKMapKit.xcodeproj/project.pbxproj
> -				SWIFT_VERSION = 4.0;
Needs to be 4.0.

2019-04-02 19:51 UTC, mxcl commented on Tests/TestMapKit.swift
> +        let rq = MKDirections.Request()
This probably needs to have a `#if swift` to maintain compatibility with older Swifts.

2019-04-02 20:58 UTC, aaronbrethorst commented
@mxcl thanks for the feedback. I made the requested changes.

2019-04-03 00:43 UTC, mxcl commented
Unfortunately we have revlock, we need CocoaPods 1.7.0-beta now to support the new attribute `swift_versions`. I will merge, this is fine IMO.

2019-04-03 00:43 UTC, merged